FROM ubuntu:latest

WORKDIR /var/www/html/
RUN apt update
COPY ./Fortinet_CA_SSL_1220222.crt /usr/local/share/ca-certificates/
RUN apt-get install ca-certificates -y
RUN update-ca-certificates
RUN apt update
RUN apt -y install software-properties-common
RUN add-apt-repository ppa:ondrej/php
RUN apt update
RUN apt install php8.1 php8.1-fpm php8.1-cli -y
RUN apt install php8.1-fpm php8.1-common php8.1-mysql php8.1-gmp php8.1-curl php8.1-intl php8.1-mbstring php8.1-xmlrpc php8.1-gd php8.1-xml php8.1-cli php8.1-zip php8.1-soap php8.1-bcmath -y
RUN apt install curl -y
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.2.10

EXPOSE 9000
CMD mkdir -p /var/run/php && php-fpm8.1 --nodaemonize --fpm-config /etc/php/8.1/fpm/php-fpm.conf



